module.exports = {
  DEAL_REASON_CLIENT: 'DEAL_REASON_CLIENT',
  DEAL_REASON_MOBILE: 'DEAL_REASON_MOBILE',
  DEAL_REASON_WEB: 'DEAL_REASON_WEB',
  DEAL_REASON_EXPERT: 'DEAL_REASON_EXPERT',
  DEAL_REASON_SL: 'DEAL_REASON_SL',
  DEAL_REASON_TP: 'DEAL_REASON_TP',
  DEAL_REASON_SO: 'DEAL_REASON_SO',
  DEAL_REASON_ROLLOVER: 'DEAL_REASON_ROLLOVER',
  DEAL_REASON_VMARGIN: 'DEAL_REASON_VMARGIN',
  DEAL_REASON_SPLIT: 'DEAL_REASON_SPLIT',
};
