module.exports = {
  ORDER_TYPE_BUY: 'ORDER_TYPE_BUY',
  ORDER_TYPE_SELL: 'ORDER_TYPE_SELL',
  ORDER_TYPE_BUY_LIMIT: 'ORDER_TYPE_BUY_LIMIT',
  ORDER_TYPE_SELL_LIMIT: 'ORDER_TYPE_SELL_LIMIT',
  ORDER_TYPE_BUY_STOP: 'ORDER_TYPE_BUY_STOP',
  ORDER_TYPE_SELL_STOP: 'ORDER_TYPE_SELL_STOP',
  ORDER_TYPE_BUY_STOP_LIMIT: 'ORDER_TYPE_BUY_STOP_LIMIT',
  ORDER_TYPE_SELL_STOP_LIMIT: 'ORDER_TYPE_SELL_STOP_LIMIT',
  ORDER_TYPE_CLOSE_BY: 'ORDER_TYPE_CLOSE_BY',
};
