module.exports = {
  ORDER_REASON_CLIENT: 'ORDER_REASON_CLIENT',
  ORDER_REASON_MOBILE: 'ORDER_REASON_MOBILE',
  ORDER_REASON_WEB: 'ORDER_REASON_WEB',
  ORDER_REASON_EXPERT: 'ORDER_REASON_EXPERT',
  ORDER_REASON_SL: 'ORDER_REASON_SL',
  ORDER_REASON_TP: 'ORDER_REASON_TP',
  ORDER_REASON_SO: 'ORDER_REASON_SO',
};
