module.exports = {
  ORDER_STATE_STARTED: 'ORDER_STATE_STARTED',
  ORDER_STATE_PLACED: 'ORDER_STATE_PLACED',
  ORDER_STATE_CANCELED: 'ORDER_STATE_CANCELED',
  ORDER_STATE_PARTIAL: 'ORDER_STATE_PARTIAL',
  ORDER_STATE_FILLED: 'ORDER_STATE_FILLED',
  ORDER_STATE_REJECTED: 'ORDER_STATE_REJECTED',
  ORDER_STATE_EXPIRED: 'ORDER_STATE_EXPIRED',
  ORDER_STATE_REQUEST_ADD: 'ORDER_STATE_REQUEST_ADD',
  ORDER_STATE_REQUEST_MODIFY: 'ORDER_STATE_REQUEST_MODIFY',
  ORDER_STATE_REQUEST_CANCEL: 'ORDER_STATE_REQUEST_CANCEL',
};
